'use client';

import { useState } from 'react';

type Project = {id:string;number:string;title:string;subtitle:string;status:string;intro:string;problem:string;approach:string;execution:string;value:string;stack:string[];steps:string[];note?:string};

const projects:Project[]=[
{id:'persynta',number:'01',title:'Persynta',subtitle:'AI Personal Follow-Through Platform',status:'Independent product build',intro:'A persistent personal AI identity designed around voice interaction, memory and follow-through — turning intentions into scheduled conversations and completed actions rather than stopping at a notification.',problem:'Reminder apps can tell a person what to do, but they do not reliably close the loop. Real tasks need confirmation, clarification, rescheduling, escalation and context-aware follow-up.',approach:'A Digital Friend identity acts as the interaction point. The system converts intent into a plan, schedules an intervention, uses tools when required, conducts a conversation, records the outcome and updates the task state.',execution:'Designed the stateful workflow around reminders, tasks, checklists, rescheduling, completion tracking, personal memory and semantic retrieval. The architecture is being developed around LLMs, voice/STT/TTS, telephony APIs, REST services, PostgreSQL, asynchronous scheduling and controlled agentic workflows.',value:'The engineering objective is dependable personal follow-through: the assistant should remember relevant context, initiate the right interaction and adapt the next step from the user response.',stack:['Agentic AI','LLMs','Voice / STT / TTS','Telephony APIs','REST APIs','PostgreSQL','Semantic Retrieval','Stateful Workflows'],steps:['Intent','Plan + schedule','Voice intervention','State + memory'],note:'Independent product build. Public wording distinguishes designed architecture and active development from production-scale claims.'},
{id:'campus',number:'02',title:'CampusSyntra',subtitle:'AI-Native Campus Operations Platform',status:'Independent product build',intro:'A unified campus application layer connecting institutional information, academic workflows and AI-assisted operations for students, faculty and administrators.',problem:'Campus information is often fragmented across departments, documents and separate systems. The problem is not only finding data; it is turning the right institutional context into the next useful academic or operational action.',approach:'CampusSyntra places an AI layer over structured institutional data and application workflows. Authentication and application permissions remain authoritative; AI assists with retrieval, generation and workflow interaction rather than becoming the security boundary.',execution:'Built the application foundation with Next.js, TypeScript, FastAPI, Python, PostgreSQL and JWT authentication. Developed structured academic models and an AI-assisted question-paper workflow driven by syllabus and assessment requirements, with structured output and validation.',value:'The target outcome is a coherent campus operating experience with less fragmented information access, faster academic workflows and a foundation for future institutional agents and automation.',stack:['Next.js','TypeScript','FastAPI','Python','PostgreSQL','JWT','LLMs','RAG','AI Agents','n8n','Docker'],steps:['User request','Auth + campus data','AI / RAG','Academic action'],note:'Independent system/product build; not presented as a university-wide production deployment.'},
{id:'invoice',number:'03',title:'Intelligent Invoice Automation',subtitle:'UiPath + Tally ERP Workflow',status:'In progress',intro:'An enterprise finance-automation workflow that converts incoming invoice PDFs into validated structured data and prepares controlled integration with Tally ERP and reconciliation.',problem:'Invoice processing combines email intake, document extraction, field validation, business rules, accounting entry and reconciliation. Manual handoffs create avoidable effort and processing risk.',approach:'UiPath handles workflow orchestration and document processing. Validation gates prevent incomplete or inconsistent invoice data from moving downstream. Tally integration is being developed through controlled XML/API communication, with exceptions separated from successful transactions.',execution:'The workflow has been tested with a Gmail-triggered invoice attachment, PDF download and text parsing. A sample invoice produced three line items — Laptop, Keyboard and Mouse — and the calculated total of ₹107,500 matched the invoice total. The validation gate is established; Tally voucher creation and end-to-end reconciliation remain in progress.',value:'The project demonstrates practical RPA, document processing, validation and enterprise-system integration rather than a generic automation demo.',stack:['UiPath','PDF Processing','Gmail / Email Intake','DataTable','Business Rules','Tally ERP','XML / HTTP','Postman','Exception Handling'],steps:['Invoice email','Extract + validate','Tally integration','Reconcile'],note:'Status is intentionally shown as In progress. The portfolio does not claim completed Tally voucher posting until that workflow is validated.'}
];

const experience=[['01','Enterprise POC delivery','10+ AI and automation POCs across 5+ client engagements; 20% POC-to-deal conversion and contribution to 2 major contracts.'],['02','Generative AI data assistants','Built Flowise, LlamaIndex and SQL-Llama based assistants for PDF, Excel, Word and CSV sources, reducing information retrieval time by 50%.'],['03','Agentic workflows & applications','Designed 5+ Agentic AI workflows and built an HR Policy Approval application using Joget, ReactJS and a GenAI Q&A assistant.'],['04','Enterprise automation','Automated Tally ERP invoice processing and ledger reconciliation for 1,000+ daily transactions, reducing manual work by 60% and processing errors by approximately 95%.'],['05','API-connected RPA','Built RPA workflows integrating Twilio, Amazon S3, Zerodha and Tally, reducing manual operational effort by 35%.'],['06','Testing & technical consulting','Used Postman and JMeter for validation and supported technical consulting, demonstrations and industrial AI / computer-vision solution discussions.']];

const events=[['2024','HPE Discover More AI','Mumbai','Enterprise AI'],['2024','NVIDIA AI Summit','Mumbai','AI ecosystem'],['2025','IMTEX','Bengaluru','Manufacturing technology'],['2025','IIMBue','Bengaluru','Business & leadership'],['2025','The 5th Edition Healthcare Summit','Bengaluru','Healthcare technology']];

const skills=[['AI Engineering','Generative AI · LLM applications · RAG · Embeddings · Semantic Search · Prompt Engineering · Structured Outputs · Agentic AI · LLM Evaluation'],['Agentic Systems','AI Agents · Tool Calling · Agent Workflows · LLM Orchestration · Memory & State · Human-in-the-Loop · Flowise · LlamaIndex'],['Application Engineering','Python · FastAPI · REST APIs · JavaScript · TypeScript · ReactJS · Next.js · SQL · PostgreSQL · JSON'],['Automation & Integration','UiPath · RPA · n8n · Workflow Automation · Webhooks · Twilio · Amazon S3 · Tally integrations · API-driven automation'],['Cloud & Delivery','AWS · Azure · Azure OpenAI Service · Docker · Linux · Git · GitHub'],['Quality & Reliability','Postman · JMeter · API Testing · Functional Testing · Integration Testing · Output Validation · Error Handling · POC Validation'],['Data & Knowledge','SQL · PostgreSQL · Document Processing · Vector Search · Knowledge Bases · ChromaDB'],['Solution Engineering','Requirements Analysis · Technical Discovery · Business Process Analysis · Solution Design · POC Development · Stakeholder Communication']];

function Arrow(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></svg>}
function MailIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg>}
function LinkedinIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4v-7a6 6 0 0 1 6-6Z"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></svg>}
function WhatsAppIcon(){return <span className="waIcon" aria-hidden="true">W</span>}
function Architecture({steps}:{steps:string[]}){return <div className="architecture"><div className="architectureLabel">SYSTEM FLOW</div><div className="flow">{steps.map((step,index)=><div className="flowItem" key={step}><span>{String(index+1).padStart(2,'0')}</span><b>{step}</b>{index<steps.length-1&&<i><Arrow/></i>}</div>)}</div></div>}
function SectionHead({eyebrow,title,description}:{eyebrow:string;title:string;description?:string}){return <div className="sectionHead"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description&&<p>{description}</p>}</div>}

export default function Home(){
 const [project,setProject]=useState('persynta');
 const activeProject=projects.find(item=>item.id===project)||projects[0];
 return <main>
  <nav className="nav"><a className="brand" href="#top">PP<span>.</span></a><div className="navlinks"><a href="#work">Work</a><a href="#experience">Experience</a><a href="#industry">Industry</a><a href="#contact">Contact</a></div><div className="navActions"><a className="resumeLink" href="/Pooja_Pansare_AI_Engineer_Resume.pdf" target="_blank" rel="noreferrer">Resume <Arrow/></a><a className="recruiterTop" href="/go/whatsapp?context=recruiter"><WhatsAppIcon/> Recruiter? WhatsApp Pooja</a></div></nav>

  <section id="top" className="hero shell"><div className="heroMain"><div className="availability"><span className="availabilityDot"/> OPEN TO RELOCATION ANYWHERE <b>|</b> OPEN TO INTERNATIONAL OPPORTUNITIES</div><p className="kicker">AI ENGINEERING · GENAI · AGENTIC AI · INTELLIGENT AUTOMATION</p><h1>Building AI systems<br/><em>that move from idea to action.</em></h1><p className="heroRole">AI Engineer <i>·</i> Generative AI <i>·</i> Agentic AI <i>·</i> Intelligent Automation</p><p className="heroLead">I connect business requirements with AI, software engineering and automation — from technical discovery and POC development to integration, validation and stakeholder-facing delivery.</p><div className="heroActions"><a className="button primary" href="#work">Explore Selected Work <Arrow/></a><a className="button secondary" href="/Pooja_Pansare_AI_Engineer_Resume.pdf" download>Download Resume <Arrow/></a></div><div className="directLinks"><a href="/go/whatsapp?context=recruiter"><WhatsAppIcon/> WhatsApp</a><a href="mailto:poojapansare1810@gmail.com"><MailIcon/> Email</a><a href="https://www.linkedin.com/in/poojapansare1810" target="_blank" rel="noreferrer"><LinkedinIcon/> LinkedIn</a></div></div><aside className="heroProof"><div className="proofOrb"/><span className="eyebrow light">PROFESSIONAL SIGNAL</span><h3>Business context + technical execution.</h3><p>Enterprise AI / RPA delivery experience combined with independent AI product and automation builds.</p><div className="metricGrid"><div><strong>10+</strong><span>AI & automation POCs</span></div><div><strong>5+</strong><span>client engagements</span></div><div><strong>200+</strong><span>stakeholders</span></div><div><strong>20%</strong><span>POC-to-deal conversion</span></div></div><div className="relocationNote">Pune, India · Available for international relocation · Employer sponsorship required</div></aside></section>

  <section className="proofStrip shell"><div><span>PROFESSIONAL PROOF</span><p>Evidence from enterprise delivery, measurable automation outcomes and stakeholder-facing solution work.</p></div><div className="proofMetric"><strong>1,000+</strong><small>daily transactions automated</small></div><div className="proofMetric"><strong>50%</strong><small>faster information retrieval</small></div><div className="proofMetric"><strong>35%</strong><small>manual effort reduction</small></div><div className="proofMetric"><strong>2</strong><small>major contracts contributed</small></div></section>

  <section className="approach shell"><SectionHead eyebrow="01 / ENGINEERING APPROACH" title="Requirement → working solution." description="Understand, design, build, integrate, validate and demonstrate."/><div className="approachFlow">{['Understand','Design','Build','Integrate','Validate','Demonstrate'].map((step,index)=><div className="approachStep" key={step}><span>{String(index+1).padStart(2,'0')}</span><b>{step}</b>{index<5&&<Arrow/>}</div>)}</div></section>

  <section id="work" className="work shell"><div className="workHeading"><SectionHead eyebrow="02 / SELECTED SYSTEMS" title="Three systems. Three engineering problems." description="Personal AI, institutional AI and enterprise automation — shown through deeper case studies."/><div className="projectSelector">{projects.map(item=><button key={item.id} className={project===item.id?'active':''} onClick={()=>setProject(item.id)}><span>{item.number}</span>{item.title}</button>)}</div></div><article className="projectCase"><div className="projectTop"><div><span className="projectNo">{activeProject.number}</span><span className="statusTag">{activeProject.status}</span></div><a className="projectAsk" href={'/go/whatsapp?project='+activeProject.id}><WhatsAppIcon/> Want to know more about this project? <Arrow/></a></div><h3>{activeProject.title}</h3><h4>{activeProject.subtitle}</h4><p className="projectIntro">{activeProject.intro}</p><Architecture steps={activeProject.steps}/><div className="caseGrid"><div><span>PROBLEM</span><p>{activeProject.problem}</p></div><div><span>SOLUTION APPROACH</span><p>{activeProject.approach}</p></div><div><span>EXECUTION</span><p>{activeProject.execution}</p></div><div><span>ENGINEERING VALUE</span><p>{activeProject.value}</p></div></div><div className="projectBottom"><div className="stack"><span>TECHNOLOGY</span>{activeProject.stack.map(item=><b key={item}>{item}</b>)}</div><div className="projectNote">{activeProject.note}</div></div><a className="projectCta" href={'/go/whatsapp?project='+activeProject.id}><span>Want to know more about {activeProject.title}?</span><strong>Ask Pooja on WhatsApp <Arrow/></strong></a></article></section>

  <section id="experience" className="experience shell"><SectionHead eyebrow="03 / PROFESSIONAL EXPERIENCE" title="Enterprise delivery, not just experimentation." description="Software development, AI / GenAI, RPA, POC delivery, technical discovery, validation, integration and stakeholder-facing solution work."/><div className="experienceLayout"><aside className="experienceMeta"><span className="eyebrow">SKYMERIC TECHNOLOGIES PVT. LTD.</span><h3>Software Developer</h3><p>AI & RPA functional scope</p><div className="experienceDate">Jan 2024 — Oct 2025<br/>Pune, India</div><div className="companyLine">Agentic AI & RPA product company<br/><b>HPE ISV Partner · NVIDIA Inception Partner</b></div></aside><div className="experienceBody"><div className="deliveryChain">{['Requirement','Discovery','Solution Design','Development','Integration','Validation','POC / Demo'].map((item,i)=><span key={item}>{item}{i<6&&<Arrow/>}</span>)}</div><div className="impactGrid">{experience.map(([num,title,text])=><article key={num}><span>{num}</span><div><h4>{title}</h4><p>{text}</p></div></article>)}</div><div className="selectedCase"><div><span className="eyebrow light">SELECTED PROFESSIONAL CASE</span><h3>Seco Tools</h3><p>On-site technical consulting for a manufacturing enterprise, demonstrating computer-vision automation for item detection and counting. The technical presentation contributed to the project proposal.</p></div><strong>Understand.<br/>Design.<br/>Demonstrate.</strong></div></div></div></section>

  <section id="industry" className="industry shell"><SectionHead eyebrow="04 / TECHNICAL & INDUSTRY REPRESENTATION" title="Five environments. One consistent role." description="Technical representation across five major Indian industry summits and exhibitions."/><div className="industryStatement"><strong>Customer context → technical understanding → solution communication → engineering execution.</strong><span>2024–2025 · 5 events · 200+ stakeholders</span></div><div className="eventTimeline">{events.map(([year,name,city,role])=><article key={name} className="eventItem"><span className="eventYear">{year}</span><div className="eventMarker"><i/></div><div className="eventCopy"><span>{role}</span><h3>{name}</h3><p>{city}</p></div></article>)}</div></section>

  <section id="capabilities" className="skills shell"><SectionHead eyebrow="05 / TECHNICAL CAPABILITIES" title="Practical engineering stack." description="Capabilities grouped around the work, not a wall of keywords."/><div className="skillsGrid">{skills.map(([title,text],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

  <section className="foundation shell"><SectionHead eyebrow="06 / FOUNDATION" title="Education, credentials and recognition."/><div className="foundationGrid"><article><span className="eyebrow">M.SC. COMPUTER APPLICATIONS</span><h3>Modern College of Arts, Science & Commerce, Pune</h3><p>Savitribai Phule Pune University · 2023–2026</p><strong>CGPA 8.11 · First Class with Distinction</strong></article><article><span className="eyebrow">BCA</span><h3>Savitribai Phule Pune University</h3><p>2019–2022</p><strong>CGPA 8.54 · Grade A+</strong></article><article className="credential"><span className="eyebrow">VERIFIED CREDENTIAL</span><h3>Artificial Intelligence Fundamentals</h3><p>IBM SkillsBuild · Issued 04 Sep 2026</p><a href="https://www.credly.com/badges/0ddde538-a7be-48f5-b16c-1c2c2f5e5da0" target="_blank" rel="noreferrer">View verified credential <Arrow/></a><hr/><h3>AWS Solution Architect & Python Training</h3><p>3Ri Technologies · Certificate of Achievement · 21 Jan 2023 · ID 22874</p></article></div><div className="recognition"><span>RECOGNITION</span><b>2× Star Performer of the Month</b><b>Client Appreciation Award — POC Excellence</b></div></section>

  <section id="contact" className="contact shell"><div className="contactPanel"><div><span className="eyebrow light">07 / RECRUITER CONTACT</span><h2>Have an AI problem worth solving?</h2><p>For AI / GenAI / Agentic AI / Intelligent Automation opportunities, technical collaboration or a serious product discussion, reach out directly.</p><div className="contactActions"><a href="/go/whatsapp?context=recruiter"><WhatsAppIcon/> WhatsApp Pooja <Arrow/></a><a href="mailto:poojapansare1810@gmail.com"><MailIcon/> Email Pooja <Arrow/></a><a href="https://www.linkedin.com/in/poojapansare1810" target="_blank" rel="noreferrer"><LinkedinIcon/> LinkedIn <Arrow/></a></div></div><div className="contactSide"><span>AVAILABLE FOR</span><b>International relocation</b><b>AI / GenAI opportunities</b><b>Agentic AI & automation</b><b>Employer-sponsored roles</b><a href="/Pooja_Pansare_AI_Engineer_Resume.pdf" download>Download Resume <Arrow/></a></div></div></section>

  <footer className="footer shell"><div><b>Pooja Kailash Pansare</b><span>AI Engineer · Generative AI · Agentic AI · Intelligent Automation</span></div><div className="footerLinks"><a href="/Pooja_Pansare_AI_Engineer_Resume.pdf">Resume</a><a href="https://www.linkedin.com/in/poojapansare1810" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/poojapansare18" target="_blank" rel="noreferrer">GitHub</a><a href="mailto:poojapansare1810@gmail.com">Email</a><a href="/go/whatsapp?context=recruiter">WhatsApp</a></div><small>© {new Date().getFullYear()} Pooja Kailash Pansare</small></footer>
 </main>;
}
